print("Pilihan")
print("Luas")
print("Keliling")
print("Keduanya")
pilih = input("Masukkan pilihan anda: ")

if (pilih == "Luas" or pilih == "luas"):
  alas_atas = input("Masukkan Alas Atas Trapesium: ")
  alas_bawah = input("Masukkan Alas Bawah Trapesium: ")
  tinggi = input("Masukkan Tinggi Trapesium: ")
  luas = float(0.5 * (int(alas_atas) + int(alas_bawah)) * int(tinggi))
  print("Luas Trapesium:", luas)
elif (pilih == "Keliling" or pilih == "keliling"):
  alas_atas = input("Masukkan Alas Atas Trapesium: ")
  alas_bawah = input("Masukkan Alas Bawah Trapesium: ")
  sisi_kanan = input("Masukkan Sisi Kanan Trapesium: ")
  sisi_kiri = input("Masukkan Sisi Kiri Trapesium: ")
  keliling = int(alas_atas) + int(alas_bawah) + int(sisi_kanan) + int(sisi_kiri)
  print("Keliling Trapesium:", keliling)
elif (pilih == "Keduanya" or pilih == "keduanya"):
  alas_atas = input("Masukkan Alas Atas Trapesium: ")
  alas_bawah = input("Masukkan Alas Bawah Trapesium: ")
  sisi_kanan = input("Masukkan Sisi Kanan Trapesium: ")
  sisi_kiri = input("Masukkan Sisi Kiri Trapesium: ")
  tinggi = input("Masukkan Tinggi Trapesium: ")
  luas = float(0.5 * (int(alas_atas) + int(alas_bawah)) * int(tinggi))
  keliling = int(alas_atas) + int(alas_bawah) + int(sisi_kanan) + int(sisi_kiri)
  print("Luas Trapesium:", luas)
  print("Keliling Trapesium:", keliling)